# Generated by Django 2.1.4 on 2020-06-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50, verbose_name='作者名字')),
                ('author_uid', models.BigIntegerField(verbose_name='作者uid')),
                ('author_sec_uid', models.CharField(max_length=100, verbose_name='作者sec_uid')),
                ('author_short_id', models.CharField(max_length=30, verbose_name='作者抖音id')),
                ('author_gender', models.CharField(max_length=30, verbose_name='作者性别')),
                ('author_sign', models.CharField(max_length=500, verbose_name='作者简介')),
                ('author_fans_num', models.IntegerField(verbose_name='作者粉丝数')),
                ('author_favorited', models.BigIntegerField(verbose_name='作者获赞数')),
                ('author_aweme_count', models.BigIntegerField(verbose_name='作者作品数')),
                ('author_unique_id', models.CharField(max_length=30, verbose_name='作者抖音号')),
            ],
            options={
                'verbose_name': '抖音作者',
                'verbose_name_plural': '抖音作者',
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('fan_name', models.CharField(max_length=50, verbose_name='粉丝名字')),
                ('fan_uid', models.BigIntegerField(verbose_name='粉丝uid')),
                ('fan_sec_uid', models.CharField(max_length=200, verbose_name='粉丝sec_uid')),
                ('fan_gender', models.IntegerField(default=3, verbose_name='粉丝性别 1：男， 2：女')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='infos.Author')),
            ],
            options={
                'verbose_name': '粉丝',
                'verbose_name_plural': '粉丝',
                'db_table': 'Fans',
            },
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['author_name'], name='Author_author__4fb45b_idx'),
        ),
    ]
