# Generated by Django 2.1.4 on 2020-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fans',
            name='fan_name',
            field=models.CharField(max_length=200, verbose_name='粉丝名字'),
        ),
    ]
