# Generated by Django 2.1.4 on 2020-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_auto_20200613_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='fans',
            name='fan_is_follow',
            field=models.IntegerField(default=0, verbose_name='是否已经关注 0：未关注， 1：正在关注, 2: 已经关注'),
        ),
    ]
